### ISSUE TITLE
Problems with gulp-sass

### ISSUE THREAD

**Issue by bcmeireles** [csgo-league/csgo-league-web#85]
Ubuntu 18.04

When installing the web interface, after running `npm i ` (step 8) I'm getting the following error (Output from the file at /npm/_logs):

```
22109 verbose pkgid node-sass@4.14.1
22110 verbose cwd /var/www/csgo-league-web
22111 verbose Linux 4.15.0-156-generic
22112 verbose argv "/usr/bin/node" "/usr/bin/npm" "i"
22113 verbose node v10.24.1
22114 verbose npm  v6.14.12
22115 error code ELIFECYCLE
22116 error errno 1
22117 error node-sass@4.14.1 postinstall: `node scripts/build.js`
22117 error Exit status 1
22118 error Failed at the node-sass@4.14.1 postinstall script.
22118 error This is probably not a problem with npm. There is likely additional logging output above.
22119 verbose exit [ 1, true ]
```

If I then try to keep going, when reaching thep 10: `gulp build` I will get the following:

```
[03:27:58] Requiring external module @babel/register
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
{ Error: Cannot find module 'gulp-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/www/csgo-league-web/gulpfile.babel.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._compile (/var/www/csgo-league-web/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (/var/www/csgo-league-web/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32) code: 'MODULE_NOT_FOUND' }
```

Any help would be appreciated, thanks.

**Comment by Shaneajm** [comment]
I can't speak to this issue exactly but I've had similar issues relating to NPM in the past. Make sure your permissions are set correctly as I've had to run the npm command with sudo in the past. It probably isn't the best solution but I've had less issues when doing the install as root.

**Comment by thboss** [comment]
try `npm i node-sass@latest`
if doesn't work:
1. Delete the package-lock.json file
2. Remove gulp-sass from package.json
3. Reinstall gulp-sass `npm i gulp-sass --save-dev`

**Comment by bcmeireles** [comment]
> try `npm i node-sass@latest` if doesn't work:
> 
> 1. Delete the package-lock.json file
> 2. Remove gulp-sass from package.json
> 3. Reinstall gulp-sass `npm i gulp-sass --save-dev`

Tried the first command, didn't work so went with the later. Still did not work. Here's what I'm getting:
![image](https://user-images.githubusercontent.com/67381633/142672844-14883834-283e-44a7-b953-73b413a51fad.png)

**Comment by Shaneajm** [comment]
Looks like `commander` requires a newer version of Node. You can try pinning it to an older version like `commander@7.2.0` or attempt the install with a newer version of Node.
